# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Hello/Desktop/FPGA/DL-UDH-K7/UDH/UDH.srcs/sources_1/ip/wrfifo/wrfifo.xci
# IP: The module: 'wrfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Hello/Desktop/FPGA/DL-UDH-K7/UDH/UDH.srcs/sources_1/ip/wrfifo/wrfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'wrfifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Hello/Desktop/FPGA/DL-UDH-K7/UDH/UDH.srcs/sources_1/ip/wrfifo/wrfifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'wrfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Hello/Desktop/FPGA/DL-UDH-K7/UDH/UDH.srcs/sources_1/ip/wrfifo/wrfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wrfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Hello/Desktop/FPGA/DL-UDH-K7/UDH/UDH.srcs/sources_1/ip/wrfifo/wrfifo.xci
# IP: The module: 'wrfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Hello/Desktop/FPGA/DL-UDH-K7/UDH/UDH.srcs/sources_1/ip/wrfifo/wrfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'wrfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Hello/Desktop/FPGA/DL-UDH-K7/UDH/UDH.srcs/sources_1/ip/wrfifo/wrfifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'wrfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Hello/Desktop/FPGA/DL-UDH-K7/UDH/UDH.srcs/sources_1/ip/wrfifo/wrfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wrfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
